// @ts-check
/**
 * ==========================================================================
 * MATCH SCHEMA VALIDATION
 * ==========================================================================
 * Validates match/game result data before storing in IndexedDB or syncing to PocketBase
 * Based on ScoreSheet.svelte saveMatch() and SyncService
 */

import { z } from 'zod';

export const PlayerScoreSchema = z.object({
    player_name: z.string().min(1, 'Player name required').max(50).transform(s => s.replace(/<[^>]*>/g, '').trim()),
    score_details: z.record(z.string(), z.number()).optional(),
    total_score: z.number(),
    user_id: z.string().optional()
});

/**
 * Single Match Result
 * Validates data from ScoreSheet Web Component
 */
export const MatchSchema = z.object({
    id: z.string().optional(),  // Generated by PocketBase or local
    local_id: z.string().optional(),
    pb_id: z.string().nullable().optional(),
    sync_status: z.enum(['local_only', 'pending', 'syncing', 'synced', 'failed']).optional(),
    created_at_local: z.string().optional(),
    updated_at_local: z.string().optional(),
    sync_error: z.string().optional(),
    game_name: z.string().min(1, 'Game name required'),
    date: z.string().datetime().or(z.string()).optional(),
    duration: z.number().min(0).optional(),
    player_scores: z.array(PlayerScoreSchema).min(1, 'At least one player required'),
    user: z.string().optional()  // PocketBase user ID
});

/**
 * Match List
 */
export const MatchListSchema = z.array(MatchSchema);

/**
 * Sync Queue Item (for background sync)
 */
export const SyncQueueItemSchema = z.object({
    id: z.string().optional(),
    type: z.literal('match'),
    data: MatchSchema,
    timestamp: z.number().optional(),
    status: z.enum(['pending', 'syncing', 'synced', 'failed']).optional(),
    retries: z.number().default(0).optional()
});

/**
 * Validate player score
 * @param {any} data
 * @returns {z.infer<typeof PlayerScoreSchema>}
 * @throws {z.ZodError}
 */
export function validatePlayerScore(data) {
    return PlayerScoreSchema.parse(data);
}

/**
 * Validate match data before saving
 * @param {any} data
 * @returns {z.infer<typeof MatchSchema>}
 * @throws {z.ZodError}
 */
export function validateMatch(data) {
    return MatchSchema.parse(data);
}

/**
 * Validate entire match list
 * @param {any} data
 * @returns {z.infer<typeof MatchListSchema>}
 * @throws {z.ZodError}
 */
export function validateMatchList(data) {
    return MatchListSchema.parse(data);
}

/**
 * Safely validate match with detailed error reporting
 * @param {any} data
 * @returns {{ valid: boolean, data?: z.infer<typeof MatchSchema>, error?: string }}
 */
export function validateMatchSafe(data) {
    try {
        return {
            valid: true,
            data: MatchSchema.parse(data)
        };
    } catch (error) {
        const err = /** @type {any} */ (error);
        return {
            valid: false,
            error: (err.errors || err.issues)?.map((/** @type {any} */ e) => `${e.path.join('.')}: ${e.message}`).join(', ') || err.message
        };
    }
}
